export const works = [
  {
    id: 1,
    title: 'Harvard Sustainability Hackathon ID',
    description: 'Scope of work: logo, poster, flyer, social media graphics, dtp',
    scope: 'Scope of work: logo, poster, flyer, social media graphics, dtp',
    img: [
      './vendors/img/HH/HH_anim.gif',
      './vendors/img/HH/hh_screen_prev.png',
      './vendors/img/HH/hh_poster_view.png',
      './vendors/img/HH/hh_flyer_view.png',
      './vendors/img/HH/hh_branding.png',
      './vendors/img/HH/hh_cards.png',
      './vendors/img/HH/hh_bag__2.png',
      './vendors/img/HH/hh_lanyard__5.png',
      './vendors/img/HH/hh_box.png',
    ],
    tools: 'AI, PS',
    tags: 'design',
  },
  {
    id: 2,
    title: 'Kuvva Wallpapers',
    description: 'Desktop and mobile wallpapers designed for Kuvva.',
    scope: 'Scope of work: character design, illustration.',
    img: [
      './vendors/img/kuvva/kuvva1.png',
      './vendors/img/kuvva/kuvva_anim.gif',
      './vendors/img/kuvva/kuvva2.png',
      './vendors/img/kuvva/kuvva3.png',
      './vendors/img/kuvva/kuvva4.png',
      './vendors/img/kuvva/kuvva5.png',
      './vendors/img/kuvva/kuvva6.png',
      './vendors/img/kuvva/kuvva7.png',
      './vendors/img/kuvva/kuvva8.png',
    ],
    tools: 'AI',
    tags: 'design',
  },
  {
    id: 3,
    title: 'LINE Mobile Wallpapers',
    description: 'Series of mobile wallpapers designed for LINE Deco App.',
    scope: 'Scope of work: character design, illustration.',
    img: [
      './vendors/img/line/line6.png',
      './vendors/img/line/line1.png',
      './vendors/img/line/line2.png',
      './vendors/img/line/line3.png',
      './vendors/img/line/line4.png',
      './vendors/img/line/line5.png',
    ],
    tools: 'AI',
    tags: 'design',
  },
  {
    id: 4,
    title: 'Epidemic',
    description: 'Graphic / exhibition design',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/epidemic/poster.png',
      './vendors/img/epidemic/foto.png',
      './vendors/img/epidemic/epidemic__poster.png',
      './vendors/img/epidemic/epidemic1.png',
    ],
    tags: 'design',
  },
  {
    id: 5,
    title: 'Washington Post',
    description: 'Illustration',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/WP/washpost2.png',
      './vendors/img/WP/washpost1.png',
    ],
    tags: 'design',
  },
  {
    id: 6,
    title: 'Smithsonian',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/Smithsonian/smith1.png',
      './vendors/img/Smithsonian/smith2.png',
    ],
    tags: 'design',
  },
  {
    id: 7,
    title: 'Princess and the pea',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/PP/PP_anim.gif',
      './vendors/img/PP/pea1.png',
      './vendors/img/PP/pea2.png',
    ],
    tags: 'design',
  },
  {
    id: 8,
    title: 'Explorer',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/explorer/ex1.png',
      './vendors/img/explorer/ex2.png',
    ],
    tags: 'design',
  },
  {
    id: 9,
    title: 'Editorial',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/illu/k2.png',
      './vendors/img/illu/k1.png',
      './vendors/img/illu/k3.png',
      './vendors/img/illu/k4.png',
      './vendors/img/illu/helpless1.png',
      './vendors/img/illu/helpless2.png',
      './vendors/img/illu/helpless3.png',
    ],
    tags: 'design',
  },
  {
    id: 10,
    title: 'Posters',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/posters/save__poster.png',
      './vendors/img/posters/save_2__poster.png',
      './vendors/img/posters/aiweiwei_movienight.png',
      './vendors/img/posters/sollewitt__poster.png',
    ],
    tags: 'design',
  },
  {
    id: 11,
    title: 'ExpatPal',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/expal/ex1.png',
    ],
    tags: 'development',
  },
  {
    id: 12,
    title: 'Webchef',
    description: 'Scope of work: UI, UX, development',
    scope: 'Scope of work: logo, poster, flyer, promotional materials - print & web, dtp',
    img: [
      './vendors/img/webchef_bc.png',
    ],
    tags: 'design',
  },
];

// export default function WokrsService() {
//   return new Promise((resolve, reject) => {
//    setTimeout(() => resolve(works), 1000))
//   });
// }
