export const works = [ // eslint-disable-line
  {
    id: 1,
    title: 'Harvard Sustainability Hackathon ID',
    description: 'Visual Identity of the first Sustainability Hackathon at Harvard',
    scope: 'Scope of work: art direction, graphic design, dtp',
    url: 'https://www.behance.net/gallery/17088813/SUSTAINABILITY-HACKATHON-Harvard',
    img: [
      './vendors/img/HH/HH_anim.gif',
      './vendors/img/HH/hh_screen_prev.jpg',
      './vendors/img/HH/hh_poster_view.jpg',
      './vendors/img/HH/hh_flyer_view.jpg',
      './vendors/img/HH/hh_branding.jpg',
      './vendors/img/HH/hh_cards.jpg',
      './vendors/img/HH/hh_bag__2.jpg',
      './vendors/img/HH/hh_lanyard__5.jpg',
      './vendors/img/HH/hh_box.jpg',
    ],
    tools: 'AI, PS',
    tags: 'design',
  }, {
    id: 2,
    title: 'Kuvva Wallpapers',
    description: 'Desktop and mobile wallpapers designed for Kuvva.',
    scope: 'Scope of work: character design, illustration, art direction',
    url: 'https://www.behance.net/gallery/15558035/WALLPAPERS-for-KUVVA',
    img: [
      './vendors/img/kuvva/kuvva1.jpg',
      './vendors/img/kuvva/kuvva_anim.gif',
      './vendors/img/kuvva/kuvva2.jpg',
      './vendors/img/kuvva/kuvva3.jpg',
      './vendors/img/kuvva/kuvva4.jpg',
      './vendors/img/kuvva/kuvva5.jpg',
      './vendors/img/kuvva/kuvva6.jpg',
      './vendors/img/kuvva/kuvva7.jpg',
      './vendors/img/kuvva/kuvva8.jpg',
    ],
    tools: 'AI',
    tags: 'design',
  }, {
    id: 3,
    title: 'LINE Mobile Wallpapers',
    description: 'Series of mobile wallpapers designed for LINE Deco App.',
    scope: 'Scope of work: character design, illustration, art direction',
    url: 'https://www.behance.net/gallery/17161511/LINE-DECO',
    img: [
      './vendors/img/line/line6.jpg',
      './vendors/img/line/line1.jpg',
      './vendors/img/line/line2.jpg',
      './vendors/img/line/line3.jpg',
      './vendors/img/line/line4.jpg',
      './vendors/img/line/line5.jpg',
    ],
    tools: 'AI',
    tags: 'design',
  }, {
    id: 4,
    title: 'Epidemic',
    description: 'Graphic / exhibition design for the Centre of Contemporary Art in Torun, PL',
    scope: 'Scope of work: art direction, graphic design - print & web materials, dtp',
    url: 'https://www.behance.net/gallery/11628893/EPIDEMIC-ID',
    img: [
      './vendors/img/epidemic/poster.jpg', './vendors/img/epidemic/foto.jpg', './vendors/img/epidemic/epidemic__poster.jpg', './vendors/img/epidemic/foto2.jpg',
    ],
    tags: 'design',
  }, {
    id: 13,
    title: 'Where is ISS?',
    description: 'Single page app built with ReactJS',
    scope: 'Scope of work: design, development',
    url: 'https://mongru.github.io/Where_is_ISS/',
    img: [
      './vendors/img/ISS/ISS1.jpg', './vendors/img/ISS/ISS3.jpg', './vendors/img/ISS/ISS_move.gif',
    ],
    tags: 'development',
  }, {
    id: 5,
    title: 'Washington Post',
    description: 'There are no perfect victims / The Washington Post Sunday Outlook section / AD Emmet Smith ',
    scope: 'Scope of work: illustration',
    img: [
      './vendors/img/WP/washpost2.jpg', './vendors/img/WP/washpost1.jpg',
    ],
    tags: 'design',
  }, {
    id: 6,
    title: 'Smithsonian',
    description: 'Cover art for Smithsonian Magazine. The cover story is about the damage and destruction of archaeological sites and artifacts of the Middle East / AD Maria Keehan',
    scope: 'Scope of work: illustration',
    url: 'https://www.behance.net/gallery/37238623/SMITHSONIAN-MAGAZINE',
    img: [
      './vendors/img/Smithsonian/smith1.jpg', './vendors/img/Smithsonian/smith2.jpg',
    ],
    tags: 'design',
  }, {
    id: 7,
    title: 'Princess and the pea',
    description: 'Fluorescent stage design for "The Princess and the Pea" The Enchanted World Puppet Theatre, Torun, PL',
    scope: 'Scope of work: creative direction, graphic design, set design',
    url: 'https://www.behance.net/gallery/7555639/The-Princess-and-the-Pea',
    img: [
      './vendors/img/PP/PP_anim.gif', './vendors/img/PP/pea1.png', './vendors/img/PP/pea2.png',
    ],
    tags: 'design',
  }, {
    id: 11,
    title: 'ExpatPal',
    description: 'Landing page for the EXPAT__PAL__1.0 app - currently in build',
    scope: 'Scope of work: UI, UX, development',
    url: 'https://github.com/mongru/EXPAT__PAL__1.0',
    img: [
      './vendors/img/expal/ex1.jpg', './vendors/img/expal/ex3.jpg', './vendors/img/expal/ex2.jpg',
    ],
    tags: 'development',
  }, {
    id: 8,
    title: 'Explorer',
    description: 'Edition of 100 postcards printed on MOO Luxe Cards. Created exclusively for the show "6 degrees" at the Light Grey Art Lab in Minneapolis',
    scope: 'Scope of work: graphic design, illustration, dtp',
    url: 'https://www.behance.net/gallery/11752401/EXPLORER',
    img: [
      './vendors/img/explorer/ex1.jpg', './vendors/img/explorer/ex2.jpg',
    ],
    tags: 'design',
  }, {
    id: 9,
    title: 'Editorial',
    description: 'Selected editorial illustrations for KONTAKT Magazine',
    scope: 'Scope of work: illustration',
    url: 'https://www.behance.net/gallery/8577805/KONTAKT-Magazine',
    img: [
      './vendors/img/illu/k2.jpg',
      './vendors/img/illu/k3.jpg',
      './vendors/img/illu/k4.jpg',
      './vendors/img/illu/helpless1.jpg',
      './vendors/img/illu/helpless2.jpg',
      './vendors/img/illu/helpless3.jpg',
    ],
    tags: 'design',
  }, {
    id: 10,
    title: 'Posters',
    description: 'Selected posters',
    scope: 'Scope of work: graphic design, dtp',
    url: '',
    img: [
      './vendors/img/posters/save__poster.jpg',
      './vendors/img/posters/save_2__poster.jpg',
      './vendors/img/posters/aiweiwei_movienight.jpg',
      './vendors/img/posters/sollewitt__poster.jpg',
      './vendors/img/posters/epi_2.jpg',
      './vendors/img/posters/epi_3.jpg',
      './vendors/img/epidemic/epidemic1.jpg',
    ],
    tags: 'design',
  }, {
    id: 12,
    title: 'Logos',
    description: 'Selection of logos for various occasions & clients',
    scope: 'Scope of work: graphic design',
    url: 'https://www.behance.net/gallery/15101569/LOGO',
    img: [
      './vendors/img/webchef/webchef_bc.jpg',
      // './vendors/img/webchef/webc1.png',
      // './vendors/img/webchef/webc2.png',
    ],
    tags: 'design',
  }, {
    id: 14,
    title: 'Vote GMO',
    description: 'Self-published poster about the influence of genetically modified foods on the human body',
    scope: 'Scope of work: graphic design',
    url: 'https://www.behance.net/gallery/17210187/American-Illustration-33',
    img: ['./vendors/img/gmo/gmo1.jpg'],
    tags: 'design',
  },
];

// export default function WorksService() {
//   return new Promise((resolve, reject) => {
//     setTimeout(() => resolve(works), 1000)
//   });
// }
